# Generated by Django 5.1.4 on 2025-02-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="intra42User",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False, default=0)),
                ("email", models.EmailField(unique=True, blank=True, null=True)),
                ("avatar", models.URLField(blank=True, null=True)),
                ("login", models.CharField(max_length=100, blank=True, null=True)),
                ("first_name", models.CharField(max_length=100, blank=True, null=True)),
                ("last_name", models.CharField(max_length=100, blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("last_login", models.DateTimeField()),
            ],
        ),
    ]