# Generated by Django 5.1.3 on 2024-11-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games_played2',
        ),
    ]
