# Generated by Django 5.1.3 on 2024-11-12 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.ManyToManyField(related_name='banned_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_of',
            field=models.ManyToManyField(related_name='friend_of_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='muted',
            field=models.ManyToManyField(related_name='muted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friends_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
