# Generated by Django 5.1.3 on 2024-11-13 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_banned_user_friend_of_user_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friend_requests_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
