# Generated by Django 5.1.3 on 2024-11-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_requests',
        ),
    ]
