# Generated by Django 5.1.3 on 2024-11-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_profile_picture_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='banned',
            new_name='blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muted',
        ),
    ]
