# Generated by Django 5.1.3 on 2024-11-21 21:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=users.models.user_avatar_path),
        ),
    ]
