# Generated by Django 5.1.4 on 2025-02-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="intra42_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="intra42_url",
        ),
    ]
