# Generated by Django 5.1.4 on 2025-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_intra42_id_remove_user_intra42_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="intra42_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="intra42_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
