# Generated by Django 5.1.4 on 2025-04-03 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_intra42_id_user_intra42_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="draws",
        ),
        migrations.RemoveField(
            model_name="user",
            name="games_played",
        ),
        migrations.RemoveField(
            model_name="user",
            name="losses",
        ),
        migrations.RemoveField(
            model_name="user",
            name="wins",
        ),
        migrations.AddField(
            model_name="user",
            name="is_playing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="pong_draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pong_games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pong_losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="pong_requests",
            field=models.ManyToManyField(
                related_name="pong_requests_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pong_wins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ttt_draws",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ttt_games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ttt_losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ttt_requests",
            field=models.ManyToManyField(
                related_name="ttt_requests_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ttt_wins",
            field=models.IntegerField(default=0),
        ),
    ]
