# Generated by Django 5.1.4 on 2025-04-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_draws_remove_user_games_played_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pong_draws",
            new_name="draws",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pong_games_played",
            new_name="games_played",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pong_losses",
            new_name="losses",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="pong_wins",
            new_name="wins",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_playing",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pong_requests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ttt_draws",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ttt_games_played",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ttt_losses",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ttt_requests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ttt_wins",
        ),
    ]
